#!/bin/bash

set -e
set -u
set -o pipefail

NVIM_PROG="${NVIM_PROG:-nvim}"
TEST="$1"
TEST_DIR="$(dirname "$1")"

INIT_VIM="$(mktemp).vim"
cat <<EOF >> "${INIT_VIM}"
function! ModeRun(lines) abort
  call setreg('x', substitute(join(a:lines, ''), '\\<[^>]\+>', '\=eval("\"".submatch(0)."\"")', 'g'), 'c')
  normal! @x
endfunction
lua << LUAEOF

local cwd = vim.api.nvim_call_function('getcwd', {})
package.path = cwd .. '/lua/?.lua;' .. package.path
vim.api.nvim_command "set noswapfile"

local p = require 'mode.path'
_G.__FILE__ = p.split("${TEST}")
_G.__DIR__ = p.split("${TEST_DIR}")
LUAEOF
verbose luafile ${TEST}
verbose lua require('mode.test').Runner:run("${TEST}")
verbose echo ""
lua << LUAEOF
  local Runner = require('mode.test').Runner
  if Runner.state.failures > 0 then
    vim.api.nvim_command [[silent cq!]]
  else
    vim.api.nvim_command [[silent quitall!]]
  end
LUAEOF
EOF

${NVIM_PROG} -u NONE --noplugin --clean -es +"verbose source ${INIT_VIM}"
rm "${INIT_VIM}"
